

package Presentacion;

import Logica.Producto;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



public class Inventario extends javax.swing.JFrame {
    
    
    public String usuario;
    
    public Inventario(String usuario) {
        initComponents();
        this.usuario=usuario;
        recargarButtonActionPerformed(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        recargarButton = new javax.swing.JButton();
        gestionarProductosButton = new javax.swing.JButton();
        VolverButton = new javax.swing.JButton();
        agregarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(238, 238, 238));
        fondo.setMinimumSize(new java.awt.Dimension(690, 430));
        fondo.setPreferredSize(new java.awt.Dimension(690, 430));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recargarButton.setText("Recargar");
        recargarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recargarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargarButtonActionPerformed(evt);
            }
        });
        fondo.add(recargarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 140, 40));

        gestionarProductosButton.setText("Gestionar productos");
        gestionarProductosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gestionarProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarProductosButtonActionPerformed(evt);
            }
        });
        fondo.add(gestionarProductosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 140, 40));

        VolverButton.setText("Volver");
        VolverButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });
        fondo.add(VolverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 140, 40));

        agregarProducto.setText("Agregar producto");
        agregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        fondo.add(agregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 140, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jScrollPane1.setViewportView(jScrollPane2);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pollo meat.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -20, 420, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recargarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargarButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        List<Producto> productos = Persistencia.ManejoDeProductos.cargarProductos(usuario);

        for (Logica.Producto p : productos) {
            Object[] fila = {
            p.getNombre(),
            p.getCodigoProducto(),
            p.getPrecio(),
            p.getCantidad()
            };
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_recargarButtonActionPerformed

    private void gestionarProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarProductosButtonActionPerformed
        // TODO add your handling code here:
        new Presentacion.GestionarProductos(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionarProductosButtonActionPerformed

    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        // TODO add your handling code here:
        new Presentacion.MenuPrincipal(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverButtonActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        // TODO add your handling code here:
        new Presentacion.AgregarProducto(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario("pepito34").setVisible(true);
            }
        });*/
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VolverButton;
    private javax.swing.JButton agregarProducto;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton gestionarProductosButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton recargarButton;
    // End of variables declaration//GEN-END:variables
}

