/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author JORGITO
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    private String usuario;
    public MenuPrincipal(String usuario) {
        this.usuario=usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JButton();
        verInventario = new javax.swing.JButton();
        generarReporte = new javax.swing.JButton();
        registrarCliente = new javax.swing.JButton();
        registrarVenta = new javax.swing.JButton();
        registrarPago = new javax.swing.JButton();
        clientesDeudores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setMinimumSize(new java.awt.Dimension(690, 430));
        fondo.setPreferredSize(new java.awt.Dimension(690, 430));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Menú principal");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 280, 40));

        CerrarSesion.setBackground(new java.awt.Color(255, 102, 102));
        CerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        CerrarSesion.setText("Cerrar sesion");
        CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        fondo.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 150, 30));

        verInventario.setBackground(new java.awt.Color(153, 255, 153));
        verInventario.setForeground(new java.awt.Color(0, 0, 0));
        verInventario.setText("Ver inventario");
        verInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInventarioActionPerformed(evt);
            }
        });
        fondo.add(verInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 150, 50));

        generarReporte.setBackground(new java.awt.Color(255, 255, 153));
        generarReporte.setForeground(new java.awt.Color(0, 0, 0));
        generarReporte.setText("Generar reporte");
        generarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReporteActionPerformed(evt);
            }
        });
        fondo.add(generarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 150, 60));

        registrarCliente.setBackground(new java.awt.Color(102, 255, 204));
        registrarCliente.setForeground(new java.awt.Color(0, 0, 0));
        registrarCliente.setText("Registrar cliente");
        registrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteActionPerformed(evt);
            }
        });
        fondo.add(registrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 160, 50));

        registrarVenta.setBackground(new java.awt.Color(102, 255, 204));
        registrarVenta.setForeground(new java.awt.Color(0, 0, 0));
        registrarVenta.setText("Registrar venta");
        registrarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVentaActionPerformed(evt);
            }
        });
        fondo.add(registrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 160, 50));

        registrarPago.setBackground(new java.awt.Color(102, 255, 204));
        registrarPago.setForeground(new java.awt.Color(0, 0, 0));
        registrarPago.setText("Registrar pago");
        registrarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPagoActionPerformed(evt);
            }
        });
        fondo.add(registrarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, 50));

        clientesDeudores.setBackground(new java.awt.Color(153, 255, 153));
        clientesDeudores.setForeground(new java.awt.Color(0, 0, 0));
        clientesDeudores.setText("Ver clientes deudores");
        clientesDeudores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesDeudoresActionPerformed(evt);
            }
        });
        fondo.add(clientesDeudores, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 150, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/F1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 270, 430));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/F1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 440));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/F1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 450, 440));

        jLabel5.setText("jLabel5");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReporteActionPerformed
        // TODO add your handling code here:
        new Presentacion.generarReporte(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_generarReporteActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas cerrar sesión?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                this.dispose(); // Cerrar esta ventana
                new PantallaInicial().setVisible(true); // Volver a pantalla de inicio
            }    
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void verInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInventarioActionPerformed
        // TODO add your handling code here:
        new Presentacion.Inventario(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verInventarioActionPerformed

    private void registrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVentaActionPerformed
        // TODO add your handling code here:
        new Presentacion.RegistrarVenta(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarVentaActionPerformed

    private void registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteActionPerformed
        // TODO add your handling code here:
        new Presentacion.RegistrarCliente(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarClienteActionPerformed

    private void registrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPagoActionPerformed
        // TODO add your handling code here:
        new Presentacion.RegistrarPago(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarPagoActionPerformed

    private void clientesDeudoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesDeudoresActionPerformed
        new Presentacion.ClientesDeudores(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clientesDeudoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal("pepito34").setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton clientesDeudores;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton generarReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton registrarCliente;
    private javax.swing.JButton registrarPago;
    private javax.swing.JButton registrarVenta;
    private javax.swing.JButton verInventario;
    // End of variables declaration//GEN-END:variables
}
