/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logica.Cliente;
import Logica.Pago;
import Persistencia.ManejoDeClientes;
import Persistencia.ManejoDePagos;
import Persistencia.ManejoDeVentas;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author JORGITO
 */
public class RegistrarPago extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPago
     */
    private Cliente clienteActual;
    private String usuario;
    public RegistrarPago(String usuario) {
        initComponents();
        this.usuario=usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedulaField = new javax.swing.JTextField();
        montoField = new javax.swing.JTextField();
        buscarCliente = new javax.swing.JButton();
        registrarPago = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SaldoPendienteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(245, 245, 245));
        fondo.setMinimumSize(new java.awt.Dimension(690, 430));
        fondo.setPreferredSize(new java.awt.Dimension(690, 430));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Saldo pendiente: ");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, 60));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Monto a pagar:");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 60));

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Registrar pago");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 240, 80));

        cedulaField.setBackground(new java.awt.Color(255, 255, 255));
        cedulaField.setText("Cedula del cliente");
        cedulaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cedulaFieldMousePressed(evt);
            }
        });
        cedulaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaFieldActionPerformed(evt);
            }
        });
        fondo.add(cedulaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 260, -1));

        montoField.setBackground(new java.awt.Color(255, 255, 255));
        montoField.setText("Monto a pagar");
        montoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                montoFieldMousePressed(evt);
            }
        });
        montoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoFieldActionPerformed(evt);
            }
        });
        fondo.add(montoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 260, -1));

        buscarCliente.setBackground(new java.awt.Color(30, 136, 229));
        buscarCliente.setForeground(new java.awt.Color(0, 0, 0));
        buscarCliente.setText("Buscar cliente");
        buscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });
        fondo.add(buscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, 50));

        registrarPago.setBackground(new java.awt.Color(56, 142, 60));
        registrarPago.setForeground(new java.awt.Color(0, 0, 0));
        registrarPago.setText("Registrar pago");
        registrarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPagoActionPerformed(evt);
            }
        });
        fondo.add(registrarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 50));

        volver.setBackground(new java.awt.Color(120, 144, 156));
        volver.setForeground(new java.awt.Color(0, 0, 0));
        volver.setText("Volver al menu");
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        fondo.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 120, 50));

        jLabel5.setBackground(new java.awt.Color(0, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cedula del cliente:");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pago 2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, -20, 780, 480));

        SaldoPendienteLabel.setBackground(new java.awt.Color(255, 255, 51));
        SaldoPendienteLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SaldoPendienteLabel.setForeground(new java.awt.Color(0, 0, 0));
        fondo.add(SaldoPendienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaFieldActionPerformed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        // TODO add your handling code here:
        String cedulaTexto = cedulaField.getText().trim();

        if (cedulaTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa la cédula del cliente.");
            return;
        }

        int cedula;
        try {
            cedula = Integer.parseInt(cedulaTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cédula inválida.");
            return;
        }

        // ✅ Este es el orden correcto:
        List<Cliente> clientes = ManejoDeClientes.cargarClientes(usuario);
        ManejoDeVentas.cargarVentas(clientes, usuario);
        ManejoDePagos.cargarPagos(clientes, usuario);

        // ✅ Buscar el cliente ya actualizado
        for (Cliente c : clientes) {
            if (c.getCedula() == cedula) {
                clienteActual = c;
                SaldoPendienteLabel.setText("$" + clienteActual.getSaldoPendiente());
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void registrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPagoActionPerformed
        // TODO add your handling code here:
       if (clienteActual == null) {
        JOptionPane.showMessageDialog(this, "Primero debes buscar un cliente.");
        return;
        }

        String montoTexto = montoField.getText().trim();
        double monto;

        try {
            monto = Double.parseDouble(montoTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Monto inválido.");
            return;
        }

        if (monto <= 0) {
            JOptionPane.showMessageDialog(this, "El monto debe ser mayor que cero.");
            return;
        }

        // ✅ Aplicar el pago al cliente en memoria
        clienteActual.aplicarPago(monto);

        //Actualizar el saldo en la GUI
        SaldoPendienteLabel.setText("$" + clienteActual.getSaldoPendiente());

        //Guardar el pago en el archivo
        Pago nuevoPago = new Pago(clienteActual, monto);
        Persistencia.ManejoDePagos.registrarPago(nuevoPago, usuario);

        // Confirmación
        JOptionPane.showMessageDialog(this, "Pago registrado correctamente.\nNuevo saldo pendiente: $" + clienteActual.getSaldoPendiente());

        // ✅ Limpiar campo de texto del monto (opcional)
        montoField.setText("");
    }//GEN-LAST:event_registrarPagoActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        new Presentacion.MenuPrincipal(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void cedulaFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedulaFieldMousePressed
        // TODO add your handling code here:
        cedulaField.setText("");
    }//GEN-LAST:event_cedulaFieldMousePressed

    private void montoFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_montoFieldMousePressed
        // TODO add your handling code here:
        montoField.setText("");
    }//GEN-LAST:event_montoFieldMousePressed

    private void montoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPago("pepito34").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SaldoPendienteLabel;
    private javax.swing.JButton buscarCliente;
    private javax.swing.JTextField cedulaField;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField montoField;
    private javax.swing.JButton registrarPago;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
