/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JOptionPane;
import Logica.Dueño;
import Persistencia.ManejoDeUsuario;

public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreCompletoField = new javax.swing.JTextField();
        nombreUsuarioField = new javax.swing.JTextField();
        contraseñaField = new javax.swing.JPasswordField();
        registrarse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(205, 205, 205));
        fondo.setMinimumSize(new java.awt.Dimension(690, 430));
        fondo.setPreferredSize(new java.awt.Dimension(690, 430));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre de usuario:");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre completo: ");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        nombreCompletoField.setBackground(new java.awt.Color(255, 255, 255));
        nombreCompletoField.setText("Ingrese su nombre completo");
        nombreCompletoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreCompletoFieldMousePressed(evt);
            }
        });
        nombreCompletoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCompletoFieldActionPerformed(evt);
            }
        });
        fondo.add(nombreCompletoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 260, 30));

        nombreUsuarioField.setBackground(new java.awt.Color(255, 255, 255));
        nombreUsuarioField.setText("Ingrese su nombre de usuario");
        nombreUsuarioField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreUsuarioFieldMousePressed(evt);
            }
        });
        fondo.add(nombreUsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 260, 30));

        contraseñaField.setBackground(new java.awt.Color(255, 255, 255));
        contraseñaField.setText("********");
        contraseñaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaFieldMousePressed(evt);
            }
        });
        contraseñaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaFieldActionPerformed(evt);
            }
        });
        fondo.add(contraseñaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 260, 30));

        registrarse.setBackground(new java.awt.Color(0, 255, 0));
        registrarse.setForeground(new java.awt.Color(0, 0, 0));
        registrarse.setText("Registrarse");
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });
        fondo.add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 140, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/F2.1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 340, 470));

        Volver.setBackground(new java.awt.Color(102, 255, 204));
        Volver.setForeground(new java.awt.Color(0, 0, 0));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        fondo.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaFieldActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        // TODO add your handling code here:
        String nombre = nombreCompletoField.getText().trim();
        String usuario = nombreUsuarioField.getText().trim();
        String contraseña = new String(contraseñaField.getPassword()).trim();
        
        if (nombre.isEmpty() || usuario.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(Registro.this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Dueño dueño = new Dueño(nombre, usuario, contraseña);
        Persistencia.ManejoDeUsuario.registrarUsuario(dueño);
        JOptionPane.showMessageDialog(Registro.this, "Dueño registrado correctamente.");
        dispose(); // Cierra la ventana
    }//GEN-LAST:event_registrarseActionPerformed

    private void nombreCompletoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCompletoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCompletoFieldActionPerformed

    private void nombreCompletoFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreCompletoFieldMousePressed
        // TODO add your handling code here:
        nombreCompletoField.setText("");
    }//GEN-LAST:event_nombreCompletoFieldMousePressed

    private void nombreUsuarioFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreUsuarioFieldMousePressed
        // TODO add your handling code here:
        nombreUsuarioField.setText("");
    }//GEN-LAST:event_nombreUsuarioFieldMousePressed

    private void contraseñaFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaFieldMousePressed
        // TODO add your handling code here:
        contraseñaField.setText("");
    }//GEN-LAST:event_contraseñaFieldMousePressed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        new Presentacion.PantallaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JPasswordField contraseñaField;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreCompletoField;
    private javax.swing.JTextField nombreUsuarioField;
    private javax.swing.JButton registrarse;
    // End of variables declaration//GEN-END:variables
}
